// Code generated by "stringer -linecomment=true -type=painterMode"; DO NOT EDIT.

package gg

import "strconv"

const _painterMode_name = "RGBAAlpha"

var _painterMode_index = [...]uint8{0, 4, 9}

func (i painterMode) String() string {
	if i < 0 || i >= painterMode(len(_painterMode_index)-1) {
		return "painterMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _painterMode_name[_painterMode_index[i]:_painterMode_index[i+1]]
}
